version: '3.3'

networks:
  default:
    external:
      name: gogs

services:
  gogs:
    container_name: gogs
    image: gogs/gogs:0.12.3
    restart: always
    ports:
      - '10080:3000'
      - '10022:22'
    environment:
      - 'TZ=Asia/Shanghai'
    volumes:
      - $PWD/data:/data
