version: '3.3'

networks:
  default:
    external:
      name: jenkins

services:
  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean:1.24.6
    restart: always
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/data:/var/jenkins_home
