version: '3.3'

networks:
  default:
    external:
      name: yapi

services:
  yapi:
    image: jayfong/yapi:1.9.2
    container_name: yapi
    ports:
      - 40001:3000
    environment:
      - YAPI_ADMIN_ACCOUNT=huangyalong@027jinqiao.com
      - YAPI_ADMIN_PASSWORD=jqkj@2021
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[]
    depends_on:
      - mongo
    links:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    volumes:
      - $PWD/data/db:/data/db
    expose:
      - 27017
    restart: unless-stopped
