version: '3.3'

networks:
  default:
    external:
      name: qwerty

services:
  zlmediakit:
    image: zlmediakit/zlmediakit:Release.last
    container_name: zlmediakit
    ports:
      - '1935:1935'
      - '5080:80'
      - '5554:554'
      - '10000:10000'
      - '10000:10000/udp'
      - '8000:8000/udp'
    environment:
      - 'TZ=Asia/Shanghai'
    restart: unless-stopped
