version: '3.3'

networks:
  default:
    external:
      name: qwerty

services:
  gogs:
    image: zhaojun1998/zfile:3.2
    container_name: zfile
    ports:
      - '5480:8080'
    environment:
      - 'TZ=Asia/Shanghai'
    volumes:
      - '$PWD/db:/root/.zfile/db'
      - '$PWD/logs:/root/.zfile/logs'
      - '$PWD/data:/root/.zfile/data'
    restart: unless-stopped
