version: '3.3'

networks:
  default:
    external:
      name: qwerty

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      - 'TZ=Asia/Shanghai'
    volumes:
      - '$PWD/data:/data/db'
    restart: unless-stopped
